apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-ingress
  namespace: wp-proyecto
  annotations:
    # Indicamos que use el controlador Nginx que ya tenemos instalado
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: wordpress.asir.local  # [PERSONALIZABLE] La URL que pondrás en tu navegador
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wordpress-service # Debe coincidir con el nombre del servicio del Paso 5
            port:
              number: 80
