# --- PARTE 1: EL SERVICIO (Acceso interno) ---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: wp-proyecto
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend # [VITAL] Filtra para conectar solo con los pods de la web
---
# --- PARTE 2: EL DESPLIEGUE (La aplicación web) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wp-proyecto
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
        - image: wordpress:latest # [PERSONALIZABLE] Versión de WP con servidor Apache
          name: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              value: wordpress-mysql    # [FIJO] El nombre del servicio de la DB que creamos
            - name: WORDPRESS_DB_USER
              value: asir               # [VITAL] Coincide con el usuario que definimos en MySQL
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password         # [VITAL] Traemos la contraseña del Secret
            - name: WORDPRESS_DB_NAME
              value: wordpress          # [FIJO] Coincide con la DB creada en el paso anterior
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html # [FIJO] Carpeta de fotos y temas de WP
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wp-pvc           # [FIJO] El PVC de 10GB que creamos al principio
