apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prueba-pvc-asir
spec:
  storageClassName: nfs-client # Aquí le decimos que use el NFS que acabamos de crear
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
